### ISSUE TITLE
Kernel source origin

### ISSUE THREAD

**Issue by thezim** [fabianishere/udm-kernel#15]
Just a general question. Where did this kernel source code come from? It does not line up with mainstream 4.19 Linux source. Is there an official kernel source provided by Ubiquiti?

**Comment by fabianishere** [comment]
The kernel sources were provided to me by Ubiquiti.  You have to send a request to opensource-requests@ui.com to obtain the GPL archives for UniFi firmware.

Since the GPL archives do not contain the Linux Git tree, I have rebased the changes onto Linux 4.19.152 (which is the base for the UDM kernel). You can see the changesets for the stock kernel here: https://github.com/fabianishere/udm-kernel/commits/flavour/stock-v4.19

**Comment by thezim** [comment]
I requested v2.4.9 for the UDM SE and receive the archive and have push it [here](https://github.com/thezim/debbox-kernel). This is the source code with build artifacts. Is this how you normally receive it? My though was to do a `make mrproper` to clean up up some, then rebase into the baseline kernel eventually.

**Comment by fabianishere** [comment]
Hmm, interesting, I received only the sources (without build artifacts) thus far. If you clean the build artifacts and rebase onto Linux 4.19.152, it should yield the same results as this repository.

**Comment by thezim** [comment]
The configs are definitely different though. The .config artifact included in the archive was the exact same as my UDM SE via `zcat /proc/config.gz`.  Diff against your stock config was significantly different. Will rebase to see if they are any diff otherwise.

**Comment by fabianishere** [comment]
I expect some differences in the config, but I don’t believe there are much changes between the UDM (Pro) kernel and the UDM SE kernel.

Let’s see what the rebase tells us!

**Comment by redpoisonv3** [comment]
sorry to but in as per say but i read ubiquity uses this https://buildroot.org/ to make their os then they customize it i hope it helps.
